### ISSUE TITLE
x64

### ISSUE THREAD

**Issue by Nummer** [OpenXRay/xray-16#112]
If you can then implement the x64.
Otherwise, I can try to do)

**Comment by nitrocaster** [comment]
It's mostly a part of [`Linux port`](../milestones/Linux port) milestone. Me and @Kaffeine will be focusing on this in near future,

**Comment by Nummer** [comment]
@nitrocaster how to get into your team?

**Comment by nitrocaster** [comment]
Fork, get things done, submit pull requests.

**Comment by galek** [comment]
already implemented of me and abramcumner.
source code was published, so i not think what this ticket is needed

**Comment by nitrocaster** [comment]
@galek could you provide a link?

**Comment by galek** [comment]
@nitrocaster, yes, sure.

You need only commits what modificated xrCPUPipe(replace ASM functions on C equalents, what already written), and 	
6295d37 commit(fix for physics in dTriColliderCommon.h. Fix for DEBUG_BREAK in xrDebugNew.cpp).

For x64 need use or LuaJIT 2 or simple Lua(not JIT).
And in xrCore is needed enable macro "DEBUG_MEMORY" for align on 8(?) 
And some modifications in:
1) Launcher(Splash - Window code)
2) Changed type in 1 template from "unsigned int" on "size_t"

It minimal, what is needed 

https://bitbucket.org/nick_galko/cop/commits/all


I can't find link on repo from abramcumner(just write to him). But i can do link on bins from him(https://yadi.sk/d/5t-1VEvJjuqCx)

**Comment by Kaffeine** [comment]
@galek At the very least, you (still) missed an issue with strings allocation:
https://github.com/OpenXRay/xray-16/commit/c9d84c1c76039280b0c532cb3ecc683713357eb7

**Comment by galek** [comment]
@Kaffeine, i not detected this issue(code was checked using /Wall and PVS-Studio)

**Comment by nitrocaster** [comment]
@galek Thanks, we'll try to sort out all these changes.

**Comment by nitrocaster** [comment]
> i not detected this issue(code was checked using /Wall and PVS-Studio)

First of all, PVS Studio is not guaranteed to detect all errors.

The only reason you haven't experienced memory corruption is because GSC devs kindly (or accidentally) allocate memory with 16 bytes of unused trailing space - see `xr_aligned_offset_malloc` [here](https://github.com/OpenXRay/xray-16/blob/dev/src/xrCore/xrMemory_subst_msvc.cpp#L61) and [here](https://github.com/OpenXRay/xray-16/blob/dev/src/xrCore/xrMemory_align.cpp#L85) (malloc return a pointer that is suitably aligned for any kind of variable).
This 'feature' may hide buffer overruns, so one need to be very careful if you'll consider removing that 16-byte tail.
