### ISSUE TITLE
Reimplement render availability detection

### ISSUE THREAD

**Issue by nitrocaster** [OpenXRay/xray-16#115]
Since we are going to support OpenGL render with its own feature levels, the reference render availability checking trick doesn't quite work: it's based on assumption that first unsupported render quality level means all the rest (greater) levels are not supported too, which is incorrect in case of Linux, where we have OpenGL only (so the engine would crash on [this `R_ASSERT`](../tree/dev/src/xrEngine/EngineAPI.cpp#L239)).

**Comment by tamlin-mike** [comment]
What a wonderful name 'SupportsAdvancedRendering'. Does that imply I can throw a scene graph at it, and get it rendered as voxels? _I_ would consider that pretty "Advanced". :-)

Yeah, we need to split up h/w support feature-wise (if even that, anymore).

**Comment by nitrocaster** [comment]
Back in 2004 R2 was really advanced, hence the name.

**Comment by tamlin-mike** [comment]
It's rather amazing to think R2 was written back in 2004. It still works (and looks good).

But I wonder, does any other part than the renderer need to know about this, or is it only xrRender needing the info, and the specific renderers (R[1-4], "GL" are to supply it)?

Additionally, while possibly obvious to us, perhaps we should change the names of the renderer DLL files? While xrRender_GL is obvious (not really, since "GL" could imply OpenGL 1.1), R[1-4] means nothing as it stands.

Perhaps change them to "xrRender_DX9", "xrRender_DX10", with a suffix if required?

**Comment by Xottab-DUTY** [comment]
I think that changing traditional names for renderers is not a good idea.

We can do custom renderers detection: Engine searches for files named xrRender_mod__something_ (for example, xrRender_mod_amk) and using it. More details have been sent to nitrocaster's email few months ago.

**Comment by CrossVR** [comment]
I also think we shouldn't rename them, GL is the only exception to the naming scheme and it is implied that it is based on the latest revision.

I'm hesitant about allowing custom renderers, there are too many inter-dependencies between the renderer and the core to make it into a plug-in system. Besides, you might as well recompile the binary if you're going to implement a custom renderer.

**Comment by CrossVR** [comment]
@Xottab-DUTY Also, please openly discuss any "details" instead of keeping them private, if you just send it to someone's private e-mail then people can't participate in the discussion.

**Comment by Xottab-DUTY** [comment]
@Armada651 the reason why the details isn't public is that i'm afraid i can incorrectly write my proposal because my English is not excellent.

**Comment by CrossVR** [comment]
@Xottab-DUTY Github is not an english exam, no one will judge you for incorrect spelling. In fact discussing it publicly might help better understand your proposal.

**Comment by Xottab-DUTY** [comment]
I suggest to change a little render detection mechanism in that way:
Load default renderers from hardcoded list (R1-R4, GL).
Then, search for files named xrRender_mod__something_, check them if they can work and display that in log (for example: custom render xrRender_mod_misery successfully loaded/failed to load.
If they can - display them in advanced options.

With that you can easily modify original render and use it without replacing original ones. This can be useful for modmakers.

**Comment by Xottab-DUTY** [comment]
So, what you can say about this, guys?

**Comment by CrossVR** [comment]
That doesn't solve the original problem, which is that we can't attempt to load DirectX renderers on Linux. And I don't think we should allow custom renderer plugins until we have a good API for the renderers without inter-dependencies with Core.

**Comment by Xottab-DUTY** [comment]
This solves problem with individual renderer check from hardcoded list - it checks R1, R2, R3, R4, RGL and getting result individually for each renderer (R1 failed.. R4 failed, RGL success).

Custom renderers that I suggest can hardly be called plug-ins, because of reason you mention. But, still, this can be handy when you need to do something with the renderer, but do not want to replace the original renderer and make a backup of it.

**Comment by CrossVR** [comment]
The hardcoded list is already there. It just needs to be refactored so it can work without all the plugins being present. The problem is the checks assume that if the worst renderer (R1) is not available, then all the others aren't available either.

This is a simply something that needs to be fixed, we don't need to completely redesign how renderer plugins are loaded (yet). If you want custom renderer plugins, then that is something for a different issue report submitted as an enhancement.

**Comment by Xottab-DUTY** [comment]
Hmm.. Basically I don't suggest completely redesign it. Bad thing that I can't explain my suggest clearly. =]

**Comment by Kahvana** [comment]
Hello guys, new to the Open-XRAY developement (just messing around with the source code in my spare time, trying to decouple GameSpy).

A random sugestion (no idea if it will even work): 
"The problem is the checks assume that if the worst renderer (R1) is not available, then all the others aren't available either." then, why not make OpenGL the worst renderer available in the list?.

**Comment by Xottab-DUTY** [comment]
Solved with commits:
[1. Refactor renderers loading system](d533f5b0350bddd27602e11a8e2f099e8171c583)
[2. New field for GEnv: CurrentRenderer](62055f2818eaa34479aea5e08960530f0ae49473)
[3. Render availability check refactor](63e2ba57c8679d8d6b467e5e7d668faf67ef8c91)
