### ISSUE TITLE
Add SMAA to renderers (R4 and RGL at least)

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#122]

**Comment by ghost** [comment]
I don't know why you feel DX11 is a priority as there's always MSAA. Anyway, K.D. of OGSE released code a while back for SMAA. I modified it a bit for R2, here it is: https://www.mediafire.com/?bcpwguyg36if2bn
And whoops, here are the shaders: https://www.mediafire.com/?dqi0h7p75myc2j6
Don't know if it's even working correctly, and never managed to configure it right for R4.

Note: You'll need to use a newer D3D compiler for DX9 in order to use the "unroll" function required by the shaders. You will also have to change all "half" values in the DX9 shaders to "float", and some other small changes.

It also isn't updated for this code base, but when I get more time I will do so. Let me know if there's any issues.

**Comment by SC1040-TS2** [comment]
As the XRay Engine does not natively support anti-aliasing, but rather uses a blurring effect to create a sort of Fake AA, I do not believe trying to implement true anti-aliasing algorithms would suffice. If they were a main focus, however, I would highly suggest trying to implement the lightweight FXAA algorithm before anything else, then consider more system-taxing methods of AA such as the one mentioned above.

Edit: I realize now that an earlier added Issue for adding FXAA exists after checking, but my point of focusing on implementation of that before even considering working on implementing this remains.

**Comment by Xottab-DUTY** [comment]
I need to say that the FXAA was already implemented by Alexey Baula and it's used in XRay Oxygen Project

**Comment by SC1040-TS2** [comment]
Huh. I wasn't aware of the XRay Oxygen Project or its existence. I'll have to look into that.

My apologies for assuming this was the only major XRay Engine project, as my research prior to now didn't lead to the discovery of that project. I think this is another case of Wikipedia's sheer unreliability.
(For context, the X-Ray Engine's Wikipedia page lists the OpenXRay Github under main websites alongside GSC, but not XRay Oxygen. That was how I ended up finding this Github in the first place.)

**Comment by Xottab-DUTY** [comment]
@SC1040-TS2 There's a [list of engine projects](https://www.gameru.net/forum/index.php?showtopic=23443) on russian site Gameru.net. Just look into the second spoiler and open the inner spoiler.

**Comment by ForserX** [comment]
@SC1040-TS2 : Oxygen: https://github.com/ForserX/xray-oxygen - x64 only, AVX.

**Comment by SC1040-TS2** [comment]
Thanks for the information. I'll take a look into both for the time being, as well as actually try to learn a bit of C++ if I have the time to. Though, @ForserX, having looked at the amount of work you've been doing on your own fork of the repository, I'm impressed by your level of recent activity and project developments. Nice work so far on the x64 port, man.

**Comment by ForserX** [comment]
@SC1040-TS2, I'm just gaining experience.

**Comment by SC1040-TS2** [comment]
I understand, @ForserX. I apologize for my earlier naïvety in praising you so highly when it was, or at least seemed to be largely unwarranted.

**Comment by Xottab-DUTY** [comment]
Closing this for now. 

May be reconsidered after implementing #492.
