### ISSUE TITLE
Filesystem portability

### ISSUE THREAD

**Issue by 0xBADEAFFE** [OpenXRay/xray-16#137]
One of the bigger issues at the moment is that the filesystem relies on WinApi functions, it should be changed to be more platform independent.

**Comment by Kaffeine** [comment]
I worked on LocatorAPI and I will continue.

WIP is available here (last two commits):
https://github.com/Kaffeine/xray-16/tree/dir_entry_wip

<s>It might not look interesting, but I made it to work and sadly had no time to polish commits.
This makes utils/mp_screenshots_info to work on Linux.</s>
I made mp_screenshots_info to work on linux, but had to time to made proper abstraction and implement its windows counterpart.

I'll do it, may be the next month.

**Comment by 0xBADEAFFE** [comment]
@Kaffeine Thank god, I thought you stopped working on xray. I'll take a look at your work.

**Comment by CrossVR** [comment]
@vincent-t Nice hearing from you, I'm currently also swamped in work but once things die down a little I'll get back working on the OpenGL backend.

**Comment by 0xBADEAFFE** [comment]
@Armada651 I hope we get the engine working on Linux this year. Your work is an very important part of this. Thank you so much! :+1:

**Comment by CrossVR** [comment]
@vincent-t Thanks, I've rewritten the OpenGL backend for Call of Pripyat. It's a much cleaner port that doesn't require as many changes in the code. In the Clear Sky OpenGL backend I've worked myself into a corner where the code has become unmaintainable, because every new feature that gets ported over from the DirectX backend required a ton of changes.

You can already run the Call of Pripyat backend in-game, but it's not on the same level yet as the Clear Sky backend.
