### ISSUE TITLE
bugfixes with PVS-Studio

### ISSUE THREAD

**Issue by alexgdi** [OpenXRay/xray-16#140]
PVS-Studio group review code x-ray.
on Russian: https://habrahabr.ru/company/pvs-studio/blog/303664/
on English: http://www.viva64.com/en/b/0405/

**Comment by TheLonerD** [comment]
Зачем? Автор и так видел статью на Хабре, и даже там отписался.
https://habrahabr.ru/company/pvs-studio/blog/303664/#comment_9666102
Вопрос только в том, что будет ли он это править. Надеюсь, что да.

**Comment by alexgdi** [comment]
@TheLonerD, исью был создан до комментария автора.

**Comment by Kaffeine** [comment]
@TheLonerD 

> Вопрос только в том, что будет ли он это править. Надеюсь, что да.

These fixes are "low-hanging fruits" and can be fixed by anyone with just a little C++ experience. Best for one, who want to contribute, but don't know where to start.

At the same time, it would be better for developers to spend time on more complex and not obvious things. If nobody will fix this in two month, then I will find a volunteer.

**Comment by revolucas** [comment]
Most of these warnings are in unused parts of code, like Multiplayer, Gamespy, third-party libraries and Level Editor tools which is why they slipped by GSC.
