### ISSUE TITLE
Trying to sleep crashes game

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#147]
I can't pinpoint where the issue lies as the error log tells me to see the stack trace. If you look at the Open Xray branch by Avotishin he had added some specific changes that would make it so the exact line in a script is indicated when a failure occurs. I'll try and find the commit.

**Comment by revolucas** [comment]
I don't know what is causing your specific crash but I do know the vanilla **ui_sleep_dialog.script** has some issues that should be addressed. It doesn't use SetAutoDelete(true) and also a group of statics are loaded into sleep_st_tbl which is scoped to the script table which can cause the game to crash if you sleep often, minimize then reload a save. self.sleep_mb also needs SetAutoDelete(true).

I think Avoitshin only moved some code that is used Debug to main release. You can see more detailed stack traces in debug but I don't know why anyone would want to test while in debug it runs like ass. Detailed logging should be enabled for Release hidden behind a command line.

**Comment by ShokerStlk** [comment]
> as the error log tells me to see the stack trace. < 
> As a temporary workaround for that - set "break_on_assert" to false in script_engine.cpp: ~raii_guard() to see old-style error log.

**Comment by ghost** [comment]
I'm thinking we should make that a permanent change. The default behavior is useless currently.
As for the error, unfortunately the merge from revolucas did not fix the bug, but I did make that change to break_on_assert and it's causing a problem in xr_effects, line 2856. I'm no good with Lua though so I don't know what the problem is.

**Comment by tsmike** [comment]
Did a bit of digging, but haven't had much luck. Fix one crash and another takes its' place :( 

Line 38:
> self.sleep_mb:self:SetAutoDelete(true) -- Should just be self.sleep_mb:SetAutoDelete(true)

Line 74:
> pos.x = self.sleep_static:GetWndPos().x+self.sleep_static:GetWidth()

Trying to modify pos.x in any way (even just a simple increment) produces a "no matching overload found" error. 

Commenting past the pos.x issue (and passing pos values from the xml file) and the game then raises an exception originating from luabind::detail::cast_error, but doesn't mention a lua line or script.

Since I'm not really familiar with luabind or openxray's modifications (or why it really hates this one file), that's as far as I can investigate it. Hope it's useful to someone.

**Comment by revolucas** [comment]
cast error? Could it be a missing header in a UI export file? I had this problem in my CoC OpenXray fork but it split before some heavy restructuring was done to Nitro's repo.

**Comment by Xottab-DUTY** [comment]
Fixed with b3e778d29b3737d5abd189c801482503790d56f4
