### ISSUE TITLE
suggestions for all Weapons lock trigger fire/safe

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#150]
add a new function that allows the Stalker locked gun by trigger.

AKM http://www.mikedudleyweapons.com/s/cc_images/teaserbox_941342883.jpg?t=1418761561
M16 http://bohicaproducts.com/wp-content/uploads/2016/06/Safe-Semi-Burst-300x225.jpg

**Comment by tobias-strenger** [comment]
why should someone lock his weapon in an ego-shooter?

**Comment by IriaSomobu** [comment]
@OCGDFS because it prevents weapon from unexpcted fire. For example, you want to examine place using sniper rifle but don't want kill anybody at this moment.

Also it is just interesting feature. And can make game more realistic with right realisation. IMHO.

**Comment by Xottab-DUTY** [comment]
This can be used with panic factor.
Example: NPC is in panic because of something and he is trying to fire. Because of panic he can occasionally fire his friend. But gun is on lock. Because of that panic getting lower for some value and friendly fire chance is lower too.

**Comment by tobias-strenger** [comment]
@iillyyaa2033  to be honest with you.. this would become the most unused feature imho. if you dont want to fire, you just dont press fire, thats it. also i can hardly imagine ppl locking/unlocking the weapons all the time to prevent accidentally firing, since there is no threat for "real" lifes.. :)

Talking about the reality part: common regulations for operational scenarios describe, that the weapon has to have a status that enables "fast fire preparedness". that means "loaded-uncocked-unlocked" in detail. so this feature is just used in non-operational cases anyway, where you would put away your weapon, or just leave the game.

**Comment by Xottab-DUTY** [comment]
Agree that it will be unused by most players.

> This can be used with panic factor.
> Example: NPC is in panic because of something and he is trying to fire. Because of panic he can occasionally fire his friend. But gun is on lock. Because of that panic getting lower for some value and friendly fire chance is lower too.

And that thing is another story... NPC, if I remember correctly, don't do friendly fire at all.
