### ISSUE TITLE
Recruit more programmers

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#153]
I think I would like to, and I hope others of you do to, start recruiting people from various programming forums, game dev forums to help make Open Xray great. 

Then people could assign themselves a different task, like maybe a couple people work on 64-bit, some more help with Vulkan, some others help trying to multi-thread a bit more.

**Comment by CrossVR** [comment]
Nah, let's just work on this with a few devs until we have an interesting development that attracts more devs. Like a new render backend or VR support.

**Comment by ghost** [comment]
That doesn't make much sense to me. It seems the idea alone of working on a game engine for a game that is already out and playable should be more than enough to attract people to the cause.

**Comment by invokr** [comment]
Found out about this project yesterday when I saw the Stalker Mod at the top of ModDB.
I'd love to help out getting this to linux, specifically porting the none-3D modules. 

How do you organize yourself regarding who's working on what / what features are prioritized, etc?

**Comment by Xottab-DUTY** [comment]
@invokr we have issues that assigned to certain person, but most of issues is not assigned. You should look at these.
We have people's that worked on Linux port, but now they inactive. You should look at their work, so you will not have to do things twice. Here they are: [Kaffeine](https://github.com/Kaffeine/xray-16), [tamlin-mike](https://github.com/tamlin-mike/xray-16), [vincent-t](https://github.com/vincent-t/xray-16)

**Comment by 0xBADEAFFE** [comment]
@Xottab-DUTY Im not inactive I just take a small break. ;) At the moment the biggest problems for linux are Render, SDL2 port, multithreading, audio and network.

**Comment by CrossVR** [comment]
@invokr I prefer to use IRC for communication, since that is the most direct line of communication. That does often mean you need to use a bouncer so you have a backlog of messages while you're away.

We could opt to use something more modern like Slack though.

**Comment by ghost** [comment]
@Armada651 Have you considered Discord.gg? Free, a lot like IRC, etc. I use it for my mod team, works beautifully. Text and voice.

**Comment by invokr** [comment]
@Armada651 I already talked to you on IRC and I'm not a fan of a Vulkan port or throwing away an OpenGL backend that already had a lot of work put into it. Vulkan support is still very limited at the moment and will probably never be there for OS X, for example, as Apple is pursuing its Metal API.

I'm also not a fan of not doing incremental pull requests for porting. If a submodule or even a compilation unit is cross-platform, do a pull request. Right now I'd have to read through all the different forks to see who ported what and where I can pick up. I don't think that's viable / a good solution for anyone who wants to help.

**Comment by CrossVR** [comment]
@invokr I'm the only one who contributed to the OpenGL backend and I'm fine throwing it away. The OpenGL backend in XRay 1.6 never rendered correctly and there is no one to finish it. Instead of letting the code rot I chose to throw it away, I also don't think it's a good idea to try and maintain 3 very different APIs within the same engine.

On the topic of MacOS support, the OpenGL backend wouldn't have worked anyway, since the version of OpenGL supported on MacOS is much too old. At some point Apple will need to support Vulkan next to their Metal API if they want to stay relevant for video gaming.

If they really want to stick to Metal we could use something like MoltenVK, though you'd be stuck with a watermark in that case.

**Comment by CrossVR** [comment]
> I'm also not a fan of not doing incremental pull requests for porting.

I'm not sure what you mean with this? Do you want everyone to just push their code onto the master branch?

**Comment by invokr** [comment]
> I'm not sure what you mean with this? Do you want everyone to just push their code onto the master branch?

Once you have ported a specific part of the engine (e.g. the filesystem, platform handling, a complicated class or anything else that is clean), and it is working on both linux and windows, you do a pull request and merge it. 

That way, everything that is ported is already part of the engine (and doesn't affect any development as it is cross platform). It's a lot easier to look at a single repo than five different ones all with different parts ported / not ported.

Right now, I'd have to look at Kaffein, vincent-t, and this repo to find out what works on linux / doesn't work. And lets say for example, I have a working linux port based on that code, the pull request would be gigantic. You'd have to literally read through code from four different people that worked on it for a year+. That's why you do things incremental.

**Comment by CrossVR** [comment]
> That's why you do things incremental.

Oh so you are in *favor* of incremental pull requests. I was confused by the double negative in your sentence, I thought you were against it.

Yeah incremental pull requests is definitely the way to go. As far as I'm concerned, if the work is not in the main repo or in a PR it might as well not exist.

**Comment by ArnCarveris** [comment]
For rendering API take look at [bgfx](https://github.com/bkaradzic/bgfx)

**Comment by CrossVR** [comment]
@ArnCarveris That API is way too limited for an advanced engine like X-Ray.

**Comment by ArnCarveris** [comment]
@Armada651 For example?

**Comment by CrossVR** [comment]
Well just to begin with, there's no support for any DX10/11-level features, so we can only port the DX9 backend.

I want to create a backend that's on-par or better than the existing DX11 backend, not one that is worse than the original for the sake of supporting a bunch of outdated platforms.

**Comment by CrossVR** [comment]
@invokr In any case, the problem is there is currently no one to lead the linux porting effort. So we only have some people working on their own.

I'm focusing on the Vulkan backend, so I can't really lead the porting effort. Though I would be fine helping review incremental PRs since I do have experience with CMake and building Linux projects.

**Comment by invokr** [comment]
@Armada651 I'm actively looking through the code. The crazy space / tabs mixing doesn't really help with that 😄 

There's some stuff (e.g. NVApi) that I'll have to look at in more detail to see how and where it is used, as it can't be ported. The same is probably true for all the Autodesk SDK's. They exist for linux, but probably won't link with any recent compilers.

As for the OpenGL backend: I ported a DirectX application a couple month ago using Valve's 'togl' project. I'll have a look at that again once I understand the render architecture in xray.

**Comment by CrossVR** [comment]
@invokr The NVAPI stuff is mostly just used to detect how many GPUs are in the system, mostly for SLI support so we can just skip that for now. I'm not completely sure about the Autodesk SDKs, I'd expect they're only used for the Editor SDK which we can also skip.

As for the OpenGL backend: Is this about MacOS support or is there another reason for you to want an OpenGL backend? You're free to try it yourself, but the render backends have a difficult architecture to work with.

**Comment by invokr** [comment]
@Armada651 It's only partially OS X related. I have a bunch of old Linux Laptops and MacBooks lying around and getting the engine to work with OpenGL 4.1 would open the door for all of those. 

Most of the people that run Linux also tend to not have the latest and best graphics card, because there is usually no use case for that (at least from my personal experience).

**Comment by lonelyfootpad** [comment]
For what it's worth. I'd love to see a Linux port and have even been experimenting with the code to that end myself... but in truth I have nowhere near the required skill level to be able to do what is required.

As a Linux developer one thing that would make it easier to get started would be if the project was setup to use CMake

**Comment by CrossVR** [comment]
@invokr In that case it's indeed an option to just do a DX9-level OpenGL backend with pre-compiled shaders. You'll be looking at porting the R2 renderer in that case, while I'm working on porting the R4 renderer.

**Comment by tomi-kr** [comment]
Hi!

So I thought I was gonna compile the game to see if I could help with this project.

But I've got a few linker errors:
 - LuaBind.lib, 
 - LuaJit.lib 
 - ETools.lib (I don't even know what this is...) 
are missing. 

Does anyone have any idea how to fix these?

**Comment by mackron** [comment]
@tom9099 It's been a while since I've done it, and I've since deleted my local copy of this project, but if my memory serves me correctly I think I remember needing to manually compile those libraries. Also, I needed to manually comment out some code in LuaBind to get it linking - a bit hacky, but it seemed to work.

The build system is actually the biggest thing stopping me from contributing to this project. Simplifying it would be helpful in attracting more developers, in my opinion.

**Comment by tomi-kr** [comment]
@mackron cheers. I'll take a look at this later. Also I've renamed the lua51 library to luajit and it "fixed" one of my problems so I'm getting closer. 

And yeah the build environment is a bit unwelcoming :)

**Comment by CrossVR** [comment]
@tom9099 Be sure to download [the collection of dependencies](https://drive.google.com/file/d/0B2mH6ffKfXjCMjRfRTZsVlBtUVE) and extract them in the Externals folder as per the [build instructions](https://github.com/OpenXRay/xray-16/blob/dev/doc/howto/build.txt).

Also, don't forget to run `git submodule update --init`.

**Comment by tomi-kr** [comment]
@Armada651 Yeah I've gone through the build instructions (lua were mentioned in the howto: `XXX nitrocaster: add LuaJIT & LuaBind instructions`)

I didn't run `git submodule update --init`, I'll give it a try when I get home.

**Comment by CrossVR** [comment]
Updating the submodules will download luajit and luabind. But you still need to build luajit manually using the Developer Command Prompt for VS2015.

After opening the Developer Command Prompt use it to go to `Externals\luajit\src` and execute `msvcbuild_all.bat`.

**Comment by revolucas** [comment]
x64 should have been a priority, but I don't think anyone interested with the project is up for the task or those who are interested do not have the knowledge to do so. Need people who are both passionate and knowledgeable to be able to fix some of the problems with X-Ray. Those kinds of people are already off working on their own builds of X-Ray and sadly not sharing with anyone.

**Comment by ghost** [comment]
There is that one x64 repo that someone made, Nick Galko I think, but it has some issues. It isn't truly 64-bit, a lot wasn't converted properly. But it's a start. If you want to have a look I can provide a link. As for sharing, I agree, it's sad. I'd go open source but the truth is pretty much everything I'm working on is already available. I also fit into the category of not having the knowledge to accomplish a lot of things. I see stuff in the code all the time that is wrong, but I don't know how to fix these things. Maybe I should start keeping notes.

**Comment by CrossVR** [comment]
@revolucas That's a bit insulting to the people who are involved, saying that they're "not up for the task". Why should x64 be a priority? The vanilla game runs fine in 32-bit, so 64-bit support just seems like a nice-to-have. I think that's the reason why no one is working on that right now.

If you want to improve performance, then the work on improving the render backends instead of 64-bit support will be much more effective at getting framerate boosts. Of course if anyone wants to work on 64-bit support they're free to do so, but I see no reason to prioritize it.

**Comment by tomi-kr** [comment]
I tried to build the game again, but now I got linker errors with Luabind...
Since people are reimplementing renderer backends I thought at least I can build the latest without too much hassle.
Can anyone share the prebuilt binaries?

**Comment by CrossVR** [comment]
@tom9099 What linker errors? Please create a separate issue report with your linker log.

**Comment by Xottab-DUTY** [comment]
@tom9099, @Armada651, I remember I have linker errors with Luabind too. The reason, for me, was forgotten include directories (Luabind include directory for xrRender_R1-4 projects as far as I remember). But yes, this is off-topic and tom9099 might got another errors so it should have another issue. =)

**Comment by ghost** [comment]
@Armada651 I can't speak for revolucas, I don't think he meant to be insulting, but anyway the thing is with many large mods, such as my mod, and his mod, we're easily hitting the barrier with 32-bit and definitely do need 64-bit. I view it as a priority as well. Of course the vanilla game runs fine with 32-bit, that's not what anyone means. The biggest part of Stalker is mods, and many of them are getting larger in scope.

**Comment by AlexTheTriHard** [comment]
Hi all,
I managed to build the whole project.
I copied the new .dll files to _bin_dbg_Win32 and ran the xrEngine found in_bin_dbg_Win32 
I saw in the upper right corner a couple of red lines (complaining about some missing .ogg file), but the game seems to work fine.) . The Steam version does display them. 
So I guess I am on the right track?
I'm off to analyze the code in the meantime.

**Comment by CrossVR** [comment]
I'm going to work on improving the build system.

**Comment by CrossVR** [comment]
@Swartz27 I'm more of a vanilla fan myself, I do use small mods to improve the experience but I never play overhaul stalker mods. That's why it's a nice-to-have for me, I don't know how others in the project feel about it.

**Comment by ghost** [comment]
@Armada651 Fair enough, to each their own. I'm going to look at the partly-64-bit repo, and see what could be done to further implement 64-bit in Open Xray but I'm going to need to do a lot more reading. Luckily I have plenty of time on my hands.

**Comment by CrossVR** [comment]
@Swartz27 I'd be happy to review any PRs regarding 64-bit, so be sure to submit a PR before you merge something.

**Comment by revolucas** [comment]
That statement was hardly insulting. X-Ray doesn't need frame rate boosts, it already runs well enough if the lua is cleaned up. Well over 100 FPS on any graphics setting with recommended specs, even CoC users using WINE say they have great performance. But mods push the memory boundaries of the engine due to it's poor resource management as well as other serious limitation with level design that only x64 will fix. Even in the vanilla game it's easy to get out of memory errors if you increase vision draw distance and grass density.

**Comment by CrossVR** [comment]
> That statement was hardly insulting.

It was at least inconsiderate. Just because there aren't enough people to work on 64-bit support doesn't mean they don't have the ability to do so.

> X-Ray doesn't need frame rate boosts

I'm not working on the render backends for framerate boosts. I'm working on the render backends because I'm interested in Vulkan and want to make Stalker cross-platform.

**Comment by revolucas** [comment]
> I'm not working on the render backends for framerate boosts.

It was in direct reply to you telling me to work on the renderer if I want to see FPS boost, not to your work. I don't know why you have some kind of stick up your ass. Swartz started the topic talking about an interest in x64, I gave my comment. The only one being inconsiderate is you.

I'm not making demands here or telling people to work on things they don't want. I simply stated that someone passionate and knowledgeable with both X-Ray and x64 implementation would be needed to satisfy the request for x64, not some programmer off the street.

**Comment by CrossVR** [comment]
> The only one being inconsiderate is you.

You're kind of defeating your own argument:

> I don't know why you have some kind of stick up your ass.

> not some programmer off the street.

**Comment by revolucas** [comment]
The title of this thread is "Recruit more programmers" Why in the world do you think I'm talking about YOU  or anyone else on this project when I said these things?

**Comment by CrossVR** [comment]
Because that's how it comes across to potential new recruits, who's going to join the project if we're saying they're "not up for the task" or that they're "programmers off the street" beforehand?

**Comment by CrossVR** [comment]
@revolucas Anyway, let's de-escalate, all you wanted to do was comment on 64-bit support and all I wanted to do was for you to consider how your comment comes across. We can agree on that, right?

On the topic of protecting code quality, we simply demand that all contributions are submitted through a PR and the PR would have to be reviewed by someone knowledgeable with X-Ray.

So to me it doesn't really matter what the contributor's experience with X-Ray is, as long as the code is of good quality and makes sense.

**Comment by Kaffeine** [comment]
@Armada651 , sincerely, you are a god of reconciliation.

And as Armada made me to comment here, there is my 2 cents:
we want to get a cross-platform engine. In other words, we want to support Linux, but also keep Windows support. The proper way would be to insert an abstraction layer above all system-dependent code and then add Linux support with commits, which only add lines with another implementation for the same abstraction. I would like to come back to the project, but there is a number of painful things:
- I need to dive into Win32 API to replace it properly.
- I need to test windows build after every change; the project is huge and there is no CI.
- Header files usually don't include dependencies, so (my) IDE unable to work properly. No highlight, no autocompletion in header files.

I tried to work on FileSystem — I re-implemented a part of LocatorAPI with posix/libstdc++, checked that mp_screenshots_info works well. Then I stuck on insertion of the abstraction and not managed to finish it.

@invokr I pushed everything what was been ready to push. I planned to implement an initial Linux port with stubs and hacks, then fix it and finally look at the diff between branches and upstream changes atomically and properly.
