### ISSUE TITLE
Freenode to Gitter

### ISSUE THREAD

**Issue by andrew-boyarshin** [OpenXRay/xray-16#175]
Freenode is an old service with a bunch of issues preventing its normal usage. Gitter on the other hand has clean UI, GitHub integration, full message history, GFM markdown in messages. Gitter is also more widely trusted by open-source repositories.

I have already created project room at <https://gitter.im/OpenXRay/xray-16>, yet it doesn't replace freenode. If we agree on migrating to gitter, I can send PR with badge to the project and complete migration (issue and PR activity webhooks).

**Comment by Xottab-DUTY** [comment]
Online chat history is a big benefit, while in IRC you need to be logged in if you don't want to miss something!

**Comment by nitrocaster** [comment]
We have already discussed that back in 2016 and decided to stick with IRC. It's simple, it's common, it doesn't require browser (same as a separate application) and it just works. Maybe @Armada651 has something to add to the topic.

**Comment by nitrocaster** [comment]
BTW, `Conventions` label is actually intended as `Coding conventions`, so it doesn't belong here.

**Comment by Xottab-DUTY** [comment]
Gitter also have separate application and doesn't require browser if you don't wan't use it.
Cannot to mention that big chat history benefit again =)
Other people can read the discussions and know about decision have been made ~N time ago without beeing logged in.

**Comment by nitrocaster** [comment]
That's it: I can use IRC through Thunderbird or HexChat, but I can't do that with Gitter.

**Comment by CrossVR** [comment]
@Xottab-DUTY If you need chat history you should get an IRC bouncer, then you can stay logged-in. There are several free bouncer services available or I could add you to my own bouncer.

I don't really see a need to switch to gitter, all experienced C++ developers I know are on IRC. The fact that Freenode is an old service that's still running after nearly 20 years just means it's reliable.

Also, since we're porting to Linux there's even more reason to use IRC, since nearly every Linux open-source project is on Freenode.

**Comment by andrew-boyarshin** [comment]
Summing it all up, there will be no attempts to move to Gitter in the near future.
