### ISSUE TITLE
Formatting your code

### ISSUE THREAD

**Issue by avoitishin** [OpenXRay/xray-16#19]
Nitro - are you using Astyle to format code? If so, please share your settings

**Comment by nitrocaster** [comment]
I used Astyle along with builtin VS formatter to fix reference code formatting. The main reason is that all upcoming commits wont include style fixes so diffs are going to be nice and clear. Since we have now all code well formatted (almost all, there're still some minor issues because that autoformatting hasn't worked out perfectly) you just write your new code and follow our coding conventions.

**Comment by avoitishin** [comment]
Strange, almost every file I edit still have original (GSC) formatting that is all over the place when it comes to styles: tabs, extra spaces, keyword placements, etc. In any case, I have tweaked my VS formatter to match what's in your guidelines and am formatting code as i go.

**Comment by nitrocaster** [comment]
All right, I've only fixed xrCore and xrEngine formatting. It would be great if you fix the rest. I'll check my formatter settings and post them here.

**Comment by andrew-boyarshin** [comment]
@nitrocaster @Armada651 close this one? Thanks to #155 and #169.
