### ISSUE TITLE
Checksums of game resources

### ISSUE THREAD

**Issue by tpimh** [OpenXRay/xray-16#303]
Please add checksums (crc32 should be enough) of game files that can't be included in this repo for copyright reasons. This should make it easier to detect bugs happening because of different game versions.

**Comment by andrew-mcmahon** [comment]
I've added a [wiki page](https://github.com/OpenXRay/xray-16/wiki/Game-Data-MD5-Hashes-(*.db)) that contains _md5sums_ for all of the main game data files (*.db)  
  
The GoG version of the game is fully up to date and DRM-free so that would be my preference.  
You can also [reclaim retail versions](https://www.gog.com/reclaim) of all three STALKER games there if you happen to own it on disc.
  
The required game data can be extracted easily using [innoextract](http://constexpr.org/innoextract/) i.e.

`$ innoextract -g setup_stalker_cop_2.1.0.17.exe`

Copy the resulting **/game** folder wherever you please and follow the installation instructions.
