### ISSUE TITLE
No Joker's PDA near the body

### ISSUE THREAD

**Issue by donizettilorenzo** [OpenXRay/xray-16#383]
Checked with a fresh new game, no PDA near Joker's body.

**Comment by Xottab-DUTY** [comment]
This is x64 bug and it's still not fixed. For now, you can travel to Yanov and back to Zaton. After that (or a few attempts) you will find PDA.

**Comment by donizettilorenzo** [comment]
Thanks man!
I see a thread below "Launch Clear Sky": so you want add a compatibility layer to CS game too? It would be awesome! (can you point me to an existing binary release of XRay engine working with CS?)

**Comment by collectioner** [comment]
@donizettilorenzo 
Hi man, yes we want it.
Will update you ASAP

**Comment by donizettilorenzo** [comment]
Still present in the lastest public build.

**Comment by Lyokanthrope** [comment]
Just poking my head in to say this still seems to be a problem.

**Comment by nitrocaster** [comment]
Currently there's an idea that this issue may be caused by low fp precision that can not be changed in runtime on x64 platform. This can be easily (at least, it looks so) tested by changing compiler option /fp:fast to /fp:precise. The case with missing PDA is probably not the only one, as later in game other objects also spawn and therefore can fall through the terrain.
