### ISSUE TITLE
Decouple OpenAL

### ISSUE THREAD

**Issue by nitrocaster** [OpenXRay/xray-16#45]
... and add it as a 3rd party library or git submodule.

**Comment by Xottab-DUTY** [comment]
It will be great to use OpenAL-Soft.

**Comment by donizettilorenzo** [comment]
Yes, is it working right now?
Cause in the cfg you can already set "snd_device" to OpenAL Soft but it seems that the game reverts to Generic Software.

**Comment by Xottab-DUTY** [comment]
OpenAL and OpenAL Soft is a different libraries. We are using OpenAL.

**Comment by donizettilorenzo** [comment]
Well, OpenAL Soft is an open source implementation of OpenAL. In original STALKER CS/CoP you can simply add soft_oal.dll to the bin dir and select it as a driver in the sound menu of the game.

**Comment by Xottab-DUTY** [comment]
> you can simply add soft_oal.dll to the bin dir

This way doesn't suit us.

**Comment by donizettilorenzo** [comment]
So you can't simply use OpenAL.dll as a router DLL (it's its main purpose by design) and let the user choose the actual OpenAL implementation? Well, the only scenario for this totally unflexible approach is the use of DSound system default device as OpenAL device (like it was in the early days of OpenAL -> 2002/2003). Or can't you simply use OpenAL Soft by default (it's open source and very complete)?

**Comment by mirh** [comment]
> OpenAL and OpenAL Soft is a different libraries. We are using OpenAL.

OpenAL Soft is a [native](https://web.archive.org/web/20051212151337/http://www.openal.org/windows_enumeration.html) implementation of the OpenAL api/standard (which, yes, it can also become "the whole" OAL in the system eventually if you replace the router dll, but still). 

What are you talking about?

**Comment by donizettilorenzo** [comment]
Up for the request (load soft_oal.dll or other implementations for OpenAL audio)
And yes, OpenAL Soft is a native implementation of the OpenAL+EFX (CPU based).

**Comment by Xottab-DUTY** [comment]
> > you can simply add soft_oal.dll to the bin dir
> 
> This way doesn't suit us.

@donizettilorenzo, sorry for this. At the time of 2019, I misunderstood you and just missed the core problem in your comment. My point was that we should not integrate OpenAL Soft into the codebase (and use it directly) or ship it with engine binaries in a way that other OAL drivers will stop to work. But now I see that you were talking about different thing:

> Cause in the cfg you can already set "snd_device" to OpenAL Soft but it seems that the game reverts to Generic Software.

So, this was a bug, which was fixed recently in dd86162b0a6d88c49ddc993636207bcd982849d0.

> you can simply add soft_oal.dll to the bin dir

Moreover, we now ship OpenAL Soft binaries with the engine so it can be used instead of Generic Software! 😊

**Comment by donizettilorenzo** [comment]
Thanks man! SO LONG :D

Il giorno dom 4 dic 2022 alle ore 22:15 Xottab_DUTY <
***@***.***> ha scritto:
