### ISSUE TITLE
Building latest release fails. All dependencies installed.

### ISSUE THREAD

**Issue by john302** [OpenXRay/xray-16#453]
I cannot build the code on Linux. I get this when building the project on Ubuntu 18.04.

I am using these build flags and gcc 8.

`CFLAGS="-march=native" CXXFLAGS="-march=native" cmake ..`

`adding  ai/trader to xrGame
adding  CdkeyDecode to xrGame
adding  ik to xrGame
adding  ui to xrGame
adding  gamespy to xrGame
adding  ../xrServerEntities to xrGame
adding  . to xrGameSpy
adding  . to xrNetServer
adding  empty to xrNetServer
adding  . to xrParticles
adding  . to xrPhysics
adding  tri-colliderknoopc to xrPhysics
adding  dcylinder to xrPhysics
adding  . to xrScriptEngine
adding  LuaStudio to xrScriptEngine
adding  . to xrSound
-- Configuring incomplete, errors occurred!
See also "/home/jason/Documents/xray-16-xd_dev/bin/CMakeFiles/CMakeOutput.log".`

There are no errors at all in the Cmake log. I have no idea how to fix this. Please use makefiles instead of cmake.

**Comment by Xottab-DUTY** [comment]
Can you give us CMakeOutput.log anyway?

**Comment by GeorgeIvlev** [comment]
@john302
Try to remove bin directory and then create it again and try to compile code.
```
cd /home/jason/Documents/xray-16-xd_dev && rm -r ./bin && mkdir bin && cd bin && CFLAGS="-march=native" CXXFLAGS="-march=native" cmake ..
```

What the version of cmake do you have? `cmake --version`
And provide us with CMakeOutput.log please.

**Comment by GeorgeIvlev** [comment]
@john302 
I'm tried your command on Ubuntu 19.04 with gcc 8.3. Project configured and compiled successfully.

**Comment by 007exe** [comment]
sudo apt install git cmake libglew-dev libfreeimage-dev liblockfile-dev libopenal-dev libtbb-dev libcrypto++-dev libpugixml-dev libogg-dev libtheora-dev libvorbis-dev libsdl2-dev liblzo2-dev libjpeg-dev libncurses5-dev libreadline-dev gcc g++ libfreeimageplus-dev libfreeimageplus3

!!!!Attention install GCC8

git clone https://github.com/OpenXRay/xray-16.git --recurse-submodules
cd xray-16
mkdir bin
cd bin 
cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ..
make
make package 
A deb gfrtn will be created that can be installed in the system. Game resources must be copied to ~/ .local/share/GSC/SCOP/
after which you can start the game using the shortcut in the start menu or by executing a command in the xr_3da console. 

It is possible to build the engine using gcc7, but this method is not recommended for this. Open CMakeLists.txt, find the line CMAKE_CXX_COMPILER_VERSION VERSION_LESS 8.0.0 and replace it with CMAKE_CXX_COMPILER_VERSION VERSION_LESS 7.4.0. I repeat this option is not recommended because the version is newer.

**Comment by john302** [comment]
007exe`s solution worked for me. Thanks.

**Comment by GeorgeIvlev** [comment]
Is issue resolved? If so, maybe we should close this issue?
