### ISSUE TITLE
Install libs in proper /usr/lib64 destination

### ISSUE THREAD

**Issue by tim77** [OpenXRay/xray-16#506]
Problem: now openxray installs libs in `/usr/lib` but there is few issues because of this so is it possible to install them into `/usr/lib64`? How to setup this during build process?

**Comment by vpelcak** [comment]
Also libs should be made executable.

**Comment by eagleivg** [comment]
Just replace all /usr/lib at /usr/lib64 in all CMakeLists.txt

So what kind of problem appears in /usr/lib?
In Linux FHS:
/usr/lib - Libraries for the binaries in /usr/bin and /usr/sbin.
/usr/lib<qual> - Alternative format libraries, e.g. /usr/lib32 for 32-bit libraries on a 64-bit machine (optional).

Therefore main place for libs in /usr/lib

**Comment by vpelcak** [comment]
By FHS you're right.
However practically you are not. Since distributions are moving away from 32 bit, /usr/lib64 became used.

For example on Gentoo I had to manually move libs there because otherwise they would not be detected.

Anyway, proper default location should be IMHO /usr/local/... just like for most of other applications and distributions would adjust it by cmake parameters in ebuild/spec file...

**Comment by eagleivg** [comment]
I think the best choice would be to pass through the variables in CMake paths for installing binaries and libraries so that the distributors themselves can set them

**Comment by tim77** [comment]
> I think the best choice would be to pass through the variables in CMake paths for installing binaries and libraries so that the distributors themselves can set them

Yep. Exactly. TY.
