### ISSUE TITLE
Clear Sky crash, mess to launch

### ISSUE THREAD

**Issue by moussechoco** [OpenXRay/xray-16#523]
Hi there. First of all i have Clear SKy on GOG.

I followed the procedure for the installation.
I need to set the game language to Russian to be in order to launch/load a game. Is that normal? I think that's not because i didn't see that anywhere. If i set in another language i crash at the beginning of the loading screen. Thanks.

In addition, the game launches " fine" the first time after changing audio to russian. But as soon as the user.ltx is created in appdata , i got no lighting at all in my next launch of the game. I just see the sky and everything is plain black around me ( in r3 mode ).

With r4, as soon as the user.ltx is created and i load my game, i see nothing except the main menu. I have the sound of the swamp and clear sky base, but i just see the main menu. Nothing else.

**Comment by Xottab-DUTY** [comment]
Russian language hard requirement was fixed in 384a5d5e9c8fae35fa9ac7e0e91b3986e26853e3.
Issues with the renderers should also be fixed with a few commits that I made this year. So, I'm taking the liberty to close this issue.

@moussechoco, please, check if mentioned issues with Clear Sky still exist in the latest December release and we need to reopen this.
