### ISSUE TITLE
Possible workaround for an ever-changing shaders_cache

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#94]
I was thinking about the fact that if we want new shaders to work we have to delete the shaders_cache each time. I'm on a SSD and I imagine it's not happy that I continually have to delete folder after folder of the shaders_cache since I'm constantly messing around with shaders. Even have the game automatically purge the shaders_cache here and there doesn't sound like a good idea to me anymore.

I had an idea, and it's not ideal. Perhaps instead of the current format of .ps, .vs, .cs, and .h files, we can instead use an approach most games use: use precompiled shaders.

Now, GSC already had done this, and it had two problems with it:
1) People couldn't modify the shaders unless they were a .h file or if it was DX9
2) They used a strange format to compile their shaders, one which I don't recognize, and it creates way too many files for one effect.

Instead perhaps for DirectX we could use the standard of using .hlsl files (or the format OpenGL uses for that OpenGL renderer being worked on) that get bundled with the source code and compiled by Visual Studio along with the rest of the project. Or someone could use FXC.exe on it's own.
I do believe it would mean needing to re-write all the shaders a bit, which is a downside, as well as some code obviously.

In terms of allowing people to modify the shaders themselves, if this were an issue the mod author could simply package the hlsl files with their release, and if someone wanted to change something they could, and then compile it with fxc.exe and they'd have their modified shader.

Thoughts on this? I know it's a bit of work, but it strikes me as a decent solution.

**Comment by ghost** [comment]
This reminds me, I believe I spotted a bug with DX10 shader compilation:
In common.h in the R3 shader directory, if DX11 isn't defined it compiles the shaders with Shader Model 3.0. If I'm not mistaken that would slow things down a bit, as I believe DirectX 10 is 4.0 and 10.1 is 4.1.

**Comment by CrossVR** [comment]
You can't do pre-compiled shaders with OpenGL, because there is no
vendor-independent byte code. Every shader that is compiled by OpenGL has a
format that is specific to the vendor and often even the driver version and
GPU model.

A much simpler and more convenient solution is to supply a command-line
argument that disables the shader cache. Something like -no_cache that you
would use as a Launch Option while you're working on the shaders.

About the DX10 shader model, in the R3 backend shader model 4 is optional,
so it's probably being changed at runtime when your GPU supports SM4. Also,
for shaders that don't use SM4 features, compiling them with SM3 is
probably fine.

**Comment by CrossVR** [comment]
If you enable this section, you'll disable the shader cache:
https://github.com/OpenXRay/xray-16/blob/master/src/Layers/xrRenderPC_R3/r3.cpp#L1444

That's probably what the devs did during development, all we have to do is
to make it a command-line option.

**Comment by ghost** [comment]
Wow, I feel like a total moron, why didn't I think of that? :P Yes, that will work. Thank you!

**Comment by Kaffeine** [comment]
Just for case: if someone is going to implement this, I would suggest to use Core.Params instead of GetCommandLine().

**Comment by tamlin-mike** [comment]
@Swartz27 About SSD wear: I once upon a time also was worried about this. 3-or-so years later my smallest (128GB) SSD has written over 3TB, and is now at a claimed "99%" lifetime. I use that little bugger even for swapfiles. I'm by now pretty sure the electronics would start to grow mold before it gives up due to NAND overwear due to writes.

**Comment by Xottab-DUTY** [comment]
Duplicate of #68
